// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.DigitalPost.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SendConsentPayloadRequest
    {
        /// <summary>
        /// Initializes a new instance of the SendConsentPayloadRequest class.
        /// </summary>
        public SendConsentPayloadRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SendConsentPayloadRequest class.
        /// </summary>
        public SendConsentPayloadRequest(string sendingSystem = default(string), string cpr = default(string), string documentType = default(string))
        {
            SendingSystem = sendingSystem;
            Cpr = cpr;
            DocumentType = documentType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sendingSystem")]
        public string SendingSystem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cpr")]
        public string Cpr { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentType")]
        public string DocumentType { get; set; }

    }
}
