// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Digitalpost.ConsoleSample.Client
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for DigitalPostClient.
    /// </summary>
    public static partial class DigitalPostClientExtensions
    {
            /// <summary>
            /// Sends a single text message to a citizen/company.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='request'>
            /// Request body
            /// </param>
            public static SendMessageResponse SendMessage(this IDigitalPostClient operations, System.Guid subscriptionId, SendMessageRequest request = default(SendMessageRequest))
            {
                return operations.SendMessageAsync(subscriptionId, request).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Sends a single text message to a citizen/company.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='request'>
            /// Request body
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<SendMessageResponse> SendMessageAsync(this IDigitalPostClient operations, System.Guid subscriptionId, SendMessageRequest request = default(SendMessageRequest), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SendMessageWithHttpMessagesAsync(subscriptionId, request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Sends a single document to a citizen/company.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='request'>
            /// Request body
            /// </param>
            public static SendMessageResponse SendDocument(this IDigitalPostClient operations, System.Guid subscriptionId, SendDocumentRequest request = default(SendDocumentRequest))
            {
                return operations.SendDocumentAsync(subscriptionId, request).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Sends a single document to a citizen/company.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='request'>
            /// Request body
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<SendMessageResponse> SendDocumentAsync(this IDigitalPostClient operations, System.Guid subscriptionId, SendDocumentRequest request = default(SendDocumentRequest), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SendDocumentWithHttpMessagesAsync(subscriptionId, request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Uploads a single file that could be add as an attachment to the message
            /// later.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='attachment'>
            /// File added to message
            /// </param>
            public static UploadAttachmentResponse UploadAttachment(this IDigitalPostClient operations, System.Guid subscriptionId, Stream attachment)
            {
                return operations.UploadAttachmentAsync(subscriptionId, attachment).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Uploads a single file that could be add as an attachment to the message
            /// later.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='attachment'>
            /// File added to message
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<UploadAttachmentResponse> UploadAttachmentAsync(this IDigitalPostClient operations, System.Guid subscriptionId, Stream attachment, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.UploadAttachmentWithHttpMessagesAsync(subscriptionId, attachment, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Retrieves digital post configuration provider assigned to the logic
            /// subscription
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='configurationId'>
            /// Id of Digital Post configuration provider
            /// </param>
            public static DigitalPostProviderConfigurationModel GetDigitalPostConfiguration(this IDigitalPostClient operations, System.Guid subscriptionId, System.Guid configurationId)
            {
                return operations.GetDigitalPostConfigurationAsync(subscriptionId, configurationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Retrieves digital post configuration provider assigned to the logic
            /// subscription
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='configurationId'>
            /// Id of Digital Post configuration provider
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<DigitalPostProviderConfigurationModel> GetDigitalPostConfigurationAsync(this IDigitalPostClient operations, System.Guid subscriptionId, System.Guid configurationId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDigitalPostConfigurationWithHttpMessagesAsync(subscriptionId, configurationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Retrieves digital post configuration providers assigned to the logic
            /// subscription
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            public static IList<DigitalPostProviderConfigurationModel> GetAllDigitalPostConfigurations(this IDigitalPostClient operations, System.Guid subscriptionId)
            {
                return operations.GetAllDigitalPostConfigurationsAsync(subscriptionId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Retrieves digital post configuration providers assigned to the logic
            /// subscription
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<DigitalPostProviderConfigurationModel>> GetAllDigitalPostConfigurationsAsync(this IDigitalPostClient operations, System.Guid subscriptionId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAllDigitalPostConfigurationsWithHttpMessagesAsync(subscriptionId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Updates existing Doc2Mail configuration and upload certificate files.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='systemId'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='callbackUrl'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            public static DigitalPostProviderConfiguration UpdateDoc2MailConfiguration(this IDigitalPostClient operations, System.Guid subscriptionId, string id = default(string), int? systemId = default(int?), string name = default(string), string environment = default(string), string callbackUrl = default(string), Stream certificate = default(Stream))
            {
                return operations.UpdateDoc2MailConfigurationAsync(subscriptionId, id, systemId, name, environment, callbackUrl, certificate).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Updates existing Doc2Mail configuration and upload certificate files.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='systemId'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='callbackUrl'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<DigitalPostProviderConfiguration> UpdateDoc2MailConfigurationAsync(this IDigitalPostClient operations, System.Guid subscriptionId, string id = default(string), int? systemId = default(int?), string name = default(string), string environment = default(string), string callbackUrl = default(string), Stream certificate = default(Stream), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.UpdateDoc2MailConfigurationWithHttpMessagesAsync(subscriptionId, id, systemId, name, environment, callbackUrl, certificate, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Adds Doc2Mail configuration and upload certificate files.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='systemId'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='callbackUrl'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            public static DigitalPostProviderConfiguration CreateDoc2MailConfiguration(this IDigitalPostClient operations, System.Guid subscriptionId, string id = default(string), int? systemId = default(int?), string name = default(string), string environment = default(string), string callbackUrl = default(string), Stream certificate = default(Stream))
            {
                return operations.CreateDoc2MailConfigurationAsync(subscriptionId, id, systemId, name, environment, callbackUrl, certificate).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Adds Doc2Mail configuration and upload certificate files.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='systemId'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='callbackUrl'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<DigitalPostProviderConfiguration> CreateDoc2MailConfigurationAsync(this IDigitalPostClient operations, System.Guid subscriptionId, string id = default(string), int? systemId = default(int?), string name = default(string), string environment = default(string), string callbackUrl = default(string), Stream certificate = default(Stream), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateDoc2MailConfigurationWithHttpMessagesAsync(subscriptionId, id, systemId, name, environment, callbackUrl, certificate, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Updates existing eboks configuration and upload certificate file to the
            /// Azure Key Vault
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='systemId'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='callbackUrl'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='certificatePassword'>
            /// </param>
            public static DigitalPostProviderConfiguration UpdateEboksConfiguration(this IDigitalPostClient operations, System.Guid subscriptionId, string id = default(string), int? systemId = default(int?), string environment = default(string), string callbackUrl = default(string), string name = default(string), Stream certificate = default(Stream), string certificatePassword = default(string))
            {
                return operations.UpdateEboksConfigurationAsync(subscriptionId, id, systemId, environment, callbackUrl, name, certificate, certificatePassword).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Updates existing eboks configuration and upload certificate file to the
            /// Azure Key Vault
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='systemId'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='callbackUrl'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='certificatePassword'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<DigitalPostProviderConfiguration> UpdateEboksConfigurationAsync(this IDigitalPostClient operations, System.Guid subscriptionId, string id = default(string), int? systemId = default(int?), string environment = default(string), string callbackUrl = default(string), string name = default(string), Stream certificate = default(Stream), string certificatePassword = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.UpdateEboksConfigurationWithHttpMessagesAsync(subscriptionId, id, systemId, environment, callbackUrl, name, certificate, certificatePassword, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Adds existing eboks configuration and upload certificate file to the Azure
            /// Key Vault
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='systemId'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='callbackUrl'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='certificatePassword'>
            /// </param>
            public static DigitalPostProviderConfiguration CreateEboksConfiguration(this IDigitalPostClient operations, System.Guid subscriptionId, string id = default(string), int? systemId = default(int?), string environment = default(string), string callbackUrl = default(string), string name = default(string), Stream certificate = default(Stream), string certificatePassword = default(string))
            {
                return operations.CreateEboksConfigurationAsync(subscriptionId, id, systemId, environment, callbackUrl, name, certificate, certificatePassword).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Adds existing eboks configuration and upload certificate file to the Azure
            /// Key Vault
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriptionId'>
            /// Id of LoGIC subscription
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='systemId'>
            /// </param>
            /// <param name='environment'>
            /// Possible values include: 'production', 'test'
            /// </param>
            /// <param name='callbackUrl'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='certificate'>
            /// </param>
            /// <param name='certificatePassword'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<DigitalPostProviderConfiguration> CreateEboksConfigurationAsync(this IDigitalPostClient operations, System.Guid subscriptionId, string id = default(string), int? systemId = default(int?), string environment = default(string), string callbackUrl = default(string), string name = default(string), Stream certificate = default(Stream), string certificatePassword = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateEboksConfigurationWithHttpMessagesAsync(subscriptionId, id, systemId, environment, callbackUrl, name, certificate, certificatePassword, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
